// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3eaM-9rffAvKiqkysNc_Aaode2jKSz8o',
    appId: '1:585387820901:web:42320c093259321e80c38c',
    messagingSenderId: '585387820901',
    projectId: 'todo-list-51c1b',
    authDomain: 'todo-list-51c1b.firebaseapp.com',
    storageBucket: 'todo-list-51c1b.firebasestorage.app',
    measurementId: 'G-82X5ZDXS7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-LDAjImLI72m4dppzYMa3gPOl-BFc-hM',
    appId: '1:585387820901:android:6ef65ae4a490a95d80c38c',
    messagingSenderId: '585387820901',
    projectId: 'todo-list-51c1b',
    storageBucket: 'todo-list-51c1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGB9y30jEFbSr0cCSKLoT9nq-jRHU33f8',
    appId: '1:585387820901:ios:26eb3515bb31457e80c38c',
    messagingSenderId: '585387820901',
    projectId: 'todo-list-51c1b',
    storageBucket: 'todo-list-51c1b.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );
}
